// require('dotenv').config();
require('dotenv').config({path: __dirname + '/./../../../../.env'});


const {

  SCELLO_NODE_ENV,
  SCELLO_DEV_PORT,
  SCELLO_DEV_SECRET_KEY,
  SCELLO_DEV_ACCESS_TOKEN_SECRET,
  SCELLO_DEV_REFRESH_TOKEN_SECRET,
  SCELLO_DEV_REFRESH_TOKEN_EXPIRATION,
  SCELLO_DEV_ACCESS_TOKEN_EXPIRATION, 
 
  SCELLO_DEV_FRONTEND_LOCAL,
  SCELLO_DEV_FRONTEND_STAGING,
  SCELLO_DEV_FRONTEND_PRODUCTION,
  SCELLO_DEV_FRONTEND_PRODUCTION_ADMIN,
  SCELLO_DEV_EXPIRATION_IN_MINUTES,

  SCELLO_DEV_DATABASE_USERNAME,
  SCELLO_DEV_DATABASE_PASSWORD,
  SCELLO_DEV_DATABASE_NAME,
  SCELLO_DEV_DATABASE_HOST,
  SCELLO_DEV_DATABASE_URL,
  SCELLO_DEV_DATABASE_DIALECT,
  
  SCELLO_DEV_FRONTEND_LOCAL_ADMIN,
  SCELLO_DEV_MAX_RETRIES,

  SCELLO_DEV_FRONTEND_STAGING_ADMIN,
 
  SCELLO_DEV_MESSAGE_FORWARDING,
  SCELLO_DEV_BACKEND_BASE_URL,
 
  
  SCELLO_DEV_ENCODING_AUTHENTICATION_SECRET,
 
  SCELLO_DEV_BCRYPT_SALT_ROUND,

} = process.env;


module.exports = {
  SCELLO_NODE_ENV,
  SCELLO_PORT: SCELLO_DEV_PORT,
  SCELLO_SECRET_KEY: SCELLO_DEV_SECRET_KEY,
  SCELLO_ACCESS_TOKEN_SECRET: SCELLO_DEV_ACCESS_TOKEN_SECRET,
  SCELLO_REFRESH_TOKEN_SECRET: SCELLO_DEV_REFRESH_TOKEN_SECRET,
  SCELLO_REFRESH_TOKEN_EXPIRATION: SCELLO_DEV_REFRESH_TOKEN_EXPIRATION,
  SCELLO_ACCESS_TOKEN_EXPIRATION: SCELLO_DEV_ACCESS_TOKEN_EXPIRATION,
 
  SCELLO_MAX_RETRIES: SCELLO_DEV_MAX_RETRIES,
  
  SCELLO_FRONTEND_LOCAL: SCELLO_DEV_FRONTEND_LOCAL,
  SCELLO_FRONTEND_STAGING: SCELLO_DEV_FRONTEND_STAGING,
  SCELLO_FRONTEND_PRODUCTION: SCELLO_DEV_FRONTEND_PRODUCTION, 
  SCELLO_FRONTEND_PRODUCTION_ADMIN: SCELLO_DEV_FRONTEND_PRODUCTION_ADMIN,
  SCELLO_EXPIRATION_IN_MINUTES: SCELLO_DEV_EXPIRATION_IN_MINUTES,

  SCELLO_DATABASE_DIALECT: SCELLO_DEV_DATABASE_DIALECT,
  SCELLO_DATABASE_USERNAME: SCELLO_DEV_DATABASE_USERNAME,
  SCELLO_DATABASE_PASSWORD: SCELLO_DEV_DATABASE_PASSWORD,
  SCELLO_DATABASE_NAME: SCELLO_DEV_DATABASE_NAME,
  SCELLO_DATABASE_HOST: SCELLO_DEV_DATABASE_HOST,
  SCELLO_DATABASE_URL: SCELLO_DEV_DATABASE_URL,
 
 
  SCELLO_FRONTEND_LOCAL_ADMIN: SCELLO_DEV_FRONTEND_LOCAL_ADMIN,

  SCELLO_FRONTEND_STAGING_ADMIN: SCELLO_DEV_FRONTEND_STAGING_ADMIN,
 
  SCELLO_MESSAGE_FORWARDING: SCELLO_DEV_MESSAGE_FORWARDING,
  SCELLO_BACKEND_BASE_URL: SCELLO_DEV_BACKEND_BASE_URL,
 
  SCELLO_ENCODING_AUTHENTICATION_SECRET: SCELLO_DEV_ENCODING_AUTHENTICATION_SECRET,


  SCELLO_BCRYPT_SALT_ROUND: SCELLO_DEV_BCRYPT_SALT_ROUND,  

};