require('dotenv').config({path: __dirname + '/./../../../../.env'});


const {

  SCELLO_NODE_ENV,
  SCELLO_TEST_PORT,
  SCELLO_TEST_SECRET_KEY,
  SCELLO_TEST_ACCESS_TOKEN_SECRET,
  SCELLO_TEST_REFRESH_TOKEN_SECRET,
  SCELLO_TEST_REFRESH_TOKEN_EXPIRATION,
  SCELLO_TEST_ACCESS_TOKEN_EXPIRATION, 
 
  SCELLO_TEST_FRONTEND_LOCAL,
  SCELLO_TEST_FRONTEND_STAGING,
  SCELLO_TEST_FRONTEND_PRODUCTION,
  SCELLO_TEST_FRONTEND_PRODUCTION_ADMIN,
  SCELLO_TEST_EXPIRATION_IN_MINUTES,

  SCELLO_TEST_DATABASE_USERNAME,
  SCELLO_TEST_DATABASE_PASSWORD,
  SCELLO_TEST_DATABASE_NAME,
  SCELLO_TEST_DATABASE_HOST,
  SCELLO_TEST_DATABASE_URL,
  SCELLO_TEST_DATABASE_DIALECT,
  
  SCELLO_TEST_FRONTEND_LOCAL_ADMIN,
  SCELLO_TEST_MAX_RETRIES,

  SCELLO_TEST_FRONTEND_STAGING_ADMIN,
 
  SCELLO_TEST_MESSAGE_FORWARDING,
  SCELLO_TEST_BACKEND_BASE_URL,
 
  
  SCELLO_TEST_ENCODING_AUTHENTICATION_SECRET,
 
  SCELLO_TEST_BCRYPT_SALT_ROUND,

} = process.env;


module.exports = {
  SCELLO_NODE_ENV,
  SCELLO_PORT: SCELLO_TEST_PORT,
  SCELLO_SECRET_KEY: SCELLO_TEST_SECRET_KEY,
  SCELLO_ACCESS_TOKEN_SECRET: SCELLO_TEST_ACCESS_TOKEN_SECRET,
  SCELLO_REFRESH_TOKEN_SECRET: SCELLO_TEST_REFRESH_TOKEN_SECRET,
  SCELLO_REFRESH_TOKEN_EXPIRATION: SCELLO_TEST_REFRESH_TOKEN_EXPIRATION,
  SCELLO_ACCESS_TOKEN_EXPIRATION: SCELLO_TEST_ACCESS_TOKEN_EXPIRATION,
 
  SCELLO_MAX_RETRIES: SCELLO_TEST_MAX_RETRIES,
  
  SCELLO_FRONTEND_LOCAL: SCELLO_TEST_FRONTEND_LOCAL,
  SCELLO_FRONTEND_STAGING: SCELLO_TEST_FRONTEND_STAGING,
  SCELLO_FRONTEND_PRODUCTION: SCELLO_TEST_FRONTEND_PRODUCTION, 
  SCELLO_FRONTEND_PRODUCTION_ADMIN: SCELLO_TEST_FRONTEND_PRODUCTION_ADMIN,
  SCELLO_EXPIRATION_IN_MINUTES: SCELLO_TEST_EXPIRATION_IN_MINUTES,

  SCELLO_DATABASE_DIALECT: SCELLO_TEST_DATABASE_DIALECT,
  SCELLO_DATABASE_USERNAME: SCELLO_TEST_DATABASE_USERNAME,
  SCELLO_DATABASE_PASSWORD: SCELLO_TEST_DATABASE_PASSWORD,
  SCELLO_DATABASE_NAME: SCELLO_TEST_DATABASE_NAME,
  SCELLO_DATABASE_HOST: SCELLO_TEST_DATABASE_HOST,
  SCELLO_DATABASE_URL: SCELLO_TEST_DATABASE_URL,
 
 
  SCELLO_FRONTEND_LOCAL_ADMIN: SCELLO_TEST_FRONTEND_LOCAL_ADMIN,

  SCELLO_FRONTEND_STAGING_ADMIN: SCELLO_TEST_FRONTEND_STAGING_ADMIN,
 
  SCELLO_MESSAGE_FORWARDING: SCELLO_TEST_MESSAGE_FORWARDING,
  SCELLO_BACKEND_BASE_URL: SCELLO_TEST_BACKEND_BASE_URL,
 
  SCELLO_ENCODING_AUTHENTICATION_SECRET: SCELLO_TEST_ENCODING_AUTHENTICATION_SECRET,


  SCELLO_BCRYPT_SALT_ROUND: SCELLO_TEST_BCRYPT_SALT_ROUND,  

};